num_episodes: -1 
seed: null
reset_cache_state: False

checkpoint: "/AutoCAT/src/rlmeta_n/outputs/2024-11-26/00-00-25/ppo_agent-9.pth"
deterministic_policy: True 

defaults:
  - env_config: hpca_ae_exp_4_1
  - model_config: transformer
