num_episodes: 1
seed: null
reset_cache_state: False

checkpoint: "/AutoCAT/src/rlmeta_n/outputs/2024-11-22/03-18-34/ppo_agent-16.pth"
deterministic_policy: True 

defaults:
  - env_config: hpca_ae_exp_4_16
  - model_config: transformer
