num_episodes: 1 
seed: null
reset_cache_state: False

checkpoint: "/AutoCAT/src/rlmeta_n/outputs/2024-12-07/00-53-25/ppo_agent-999.pth"
deterministic_policy: True 

defaults:
  - env_config: hpca_ae_exp_4_1
  - model_config: transformer
