length_violation_reward: -2.0
double_victim_access_reward: -0.01
victim_access_reward: -0.01
correct_reward: 1.0
wrong_reward: -1.0
step_reward: -0.01
scope_line_in_cache_reward: 0.2
scope_line_not_in_cache_reward: -0.2
scope_line_evicted: 0.2
scope_line_not_evicted: -0.2

verbose: 0
force_victim_hit: false
flush_inst: false
allow_victim_multi_access: true
allow_empty_victim_access: false
attacker_addr_s: 4
attacker_addr_e: 67
scope_line: 4
victim_addr_s: 0
victim_addr_e: 0
reset_limit: 1

cache_configs:
  architecture:
    word_size: 1
    block_size: 1
    write_back: true
  cache_1:
    blocks: 8
    associativity: 8
    hit_time: 1
    rep_policy: "plru"
  cache_1_core_2:
    blocks: 8
    associativity: 8
    hit_time: 1
    rep_policy: "plru"
  cache_2:
    blocks: 8
    associativity: 4
    hit_time: 501
    rep_policy: "lru"
  cache_2_core_2:
    blocks: 8
    associativity: 4
    hit_time: 501
    rep_polocy: "plru"
  cache_3:
    blocks: 16
    associativity: 16
    hit_time: 501
    rep_policy: "plru"
  mem:
    hit_time: 1000

window_size: 384
